server:
  port: 8080
spring:
  application:
    name: "ScaffoldMueblesSasStats"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  rabbitmq:
    virtual-host: /
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
aws:
  dynamodb:
    endpoint: "http://localhost:8000"
  region: "us-east-1"
app:
  async:
    createTopology: true
    listenReplies: true
